# Common build variables for DRIVE Update V3.
# Replaces the nvdefs.mk dependency with explicit Docker-internal paths.
# This file is included by each subdirectory Makefile via: include ../common.mk

NV_DRIVE_LINUX := /drive/drive-linux
NV_TOOLCHAIN   := /drive/toolchains/aarch64--glibc--bleeding-edge-2024.02-1/bin/aarch64-buildroot-linux-gnu-

CC       := $(NV_TOOLCHAIN)gcc
CXX      := $(NV_TOOLCHAIN)g++
AR       := $(NV_TOOLCHAIN)ar
LD       := $(CC)
CROSSBIN := $(NV_TOOLCHAIN)

NV_OPT    := -Os
NV_CFLAGS := -O2 -fomit-frame-pointer -finline-functions -finline-limit=300 \
             -fgcse-after-reload -fno-strict-aliasing -Wall -MMD -MP \
             -mharden-sls=all -Wcast-align

NV_SDK_INC_DIR := $(NV_DRIVE_LINUX)/include
NV_SDK_LIB_DIR := $(NV_DRIVE_LINUX)/lib-target
NV_TARGETFS    := $(NV_DRIVE_LINUX)/targetfs

NV_SDK_INC    := -I$(NV_SDK_INC_DIR)
NV_SDK_LIB    := -L$(NV_SDK_LIB_DIR) -Wl,-rpath-link=$(NV_SDK_LIB_DIR)
NV_TARGET_LIB := -L$(NV_TARGETFS)/lib \
                 -L$(NV_TARGETFS)/usr/lib \
                 -L$(NV_TARGETFS)/usr/lib/tls \
                 -Xlinker -rpath-link -Xlinker $(NV_TARGETFS)/lib \
                 -Xlinker -rpath-link -Xlinker $(NV_TARGETFS)/usr/lib \
                 -Xlinker -rpath-link -Xlinker $(NV_TARGETFS)/usr/lib/tls
NV_LDFLAGS    := -Wl,--dynamic-linker=/lib/ld-linux-aarch64.so.1

# SRC_ROOT: root of the src/ tree (the directory containing this file).
# Works correctly after docker cp because it uses the absolute path of this file.
SRC_ROOT := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))

NV_DU_INC := $(NV_SDK_INC) -I$(SRC_ROOT) -I$(NV_SDK_INC_DIR)/dus-client -I$(NV_SDK_INC_DIR)/driveupdate

# Include dependency files generated by -MMD -MP
-include *.d
